/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 04/08/2020 17:28:04
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     48000000
#define MX_HCLKFreq_Value                       48000000
#define MX_FCLKCortexFreq_Value                 48000000
#define MX_CortexFreq_Value                     48000000
#define MX_AHBFreq_Value                        48000000
#define MX_APB1Freq_Value                       48000000
#define MX_APB2Freq_Value                       48000000
#define MX_APB1TimFreq_Value                    48000000
#define MX_APB2TimFreq_Value                    48000000
#define MX_EthernetFreq_Value                   48000000
#define MX_CECFreq_Value                        32786
#define MX_LCDTFToutputFreq_Value               48000000
#define MX_I2C1Freq_Value                       48000000
#define MX_I2C2Freq_Value                       48000000
#define MX_I2C3Freq_Value                       48000000
#define MX_I2C4Freq_Value                       48000000
#define MX_I2SFreq_Value                        96000000
#define MX_SAI1Freq_Value                       96000000
#define MX_SAI2Freq_Value                       96000000
#define MX_SDMMCFreq_Value                      48000000
#define MX_RTCFreq_Value                        32000
#define MX_USART1Freq_Value                     48000000
#define MX_USART2Freq_Value                     48000000
#define MX_USART3Freq_Value                     48000000
#define MX_UART4Freq_Value                      48000000
#define MX_UART5Freq_Value                      48000000
#define MX_UART8Freq_Value                      48000000
#define MX_UART7Freq_Value                      48000000
#define MX_USART6Freq_Value                     48000000
#define MX_USBFreq_Value                        96000000
#define MX_WatchDogFreq_Value                   32000
#define MX_LPTIM1Freq_Value                     48000000
#define MX_SPDIFRXFreq_Value                    96000000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    48000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM2_IRQn */
#define MX_TIM2_IRQn_interruptPremptionPriority 0
#define MX_TIM2_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM2_IRQn_Subriority                 0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB0 */
#define MX_PB0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB0_Pin                              PB0
#define MX_PB0_GPIOx                            GPIOB
#define MX_PB0_PinState                         GPIO_PIN_RESET
#define MX_PB0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB0_GPIO_Pin                         GPIO_PIN_0
#define MX_PB0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

